src: 
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/all.train.en
tgt: 
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/all.train.fr
domain:
        - 0
eval_src:
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/UFAL.med.en-fr.dev.en
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/ECB.en-fr.dev.en
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/IT.en-fr.dev.en
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/JRC-Acquis.en-fr.dev.en
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/Tanzil.en-fr.dev.en
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/TED2013.en-fr.dev.en

eval_ref:
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/UFAL.med.en-fr.dev.fr
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/ECB.en-fr.dev.fr
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/IT.en-fr.dev.fr
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/JRC-Acquis.en-fr.dev.fr
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/Tanzil.en-fr.dev.fr
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/TED2013.en-fr.dev.fr

eval_domain:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5

src_vocab: /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/vocab.en_fr
tgt_vocab: /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/vocab.en_fr
model_dir: /mnt/beegfs/home/pham/multi-domain-nmt/meta_learning/DAFE/models/config_100

batch_train_size: 12288
batch_test_size: 30
batch_type: tokens
experiment: baseline
step_duration: 8