src: 
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/UFAL.med.en-fr.train.en
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/ECB.en-fr.train.en
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/IT.en-fr.train.en
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/JRC-Acquis.en-fr.train.en
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/Tanzil.en-fr.train.en
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/TED2013.en-fr.train.en
tgt: 
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/UFAL.med.en-fr.train.fr
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/ECB.en-fr.train.fr
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/IT.en-fr.train.fr
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/JRC-Acquis.en-fr.train.fr
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/Tanzil.en-fr.train.fr
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/TED2013.en-fr.train.fr
domain:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
eval_src:
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/UFAL.med.en-fr.dev.en
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/ECB.en-fr.dev.en
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/IT.en-fr.dev.en
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/JRC-Acquis.en-fr.dev.en
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/Tanzil.en-fr.dev.en
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/TED2013.en-fr.dev.en
eval_ref:
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/UFAL.med.en-fr.dev.fr
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/ECB.en-fr.dev.fr
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/IT.en-fr.dev.fr
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/JRC-Acquis.en-fr.dev.fr
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/Tanzil.en-fr.dev.fr
        - /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/TED2013.en-fr.dev.fr
eval_domain:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5

src_vocab: /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/vocab.en_fr
tgt_vocab: /mnt/beegfs/home/pham/multi-domain-nmt/clean_data/vocab.en_fr
model_dir: /mnt/beegfs/home/pham/multi-domain-nmt/meta_learning/DAFE/models/practice